version: '3.8'

services:
  web_dev:
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db_dev
      - redis
  db_dev:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=core
      - POSTGRES_DB=core_dev
  redis:
    image: redis:alpine
  celery_dev:
    build: ./app
    command: celery --app=core worker --loglevel=info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - web_dev
      - redis
  celery-beat_dev:
    build: ./app
    command: celery --app=core beat --loglevel=info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - web_dev
      - redis

volumes:
  postgres_data_dev:
