# Generated by Django 3.2.9 on 2021-11-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_id', models.CharField(max_length=100)),
                ('pipeline', models.CharField(max_length=100)),
                ('exit_status', models.CharField(blank=True, max_length=50)),
                ('pipeline_command', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='date started')),
            ],
        ),
    ]
