# Generated by Django 3.2.9 on 2021-11-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='exit_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='pipeline_command',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
