# Generated by Django 3.2.9 on 2021-11-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_auto_20211117_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='date ended'),
        ),
    ]
