# Generated by Django 3.2.9 on 2021-11-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_run_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='end_time',
        ),
    ]
