# Generated by Django 3.2.9 on 2021-11-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0004_remove_run_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='start_time',
            field=models.DateTimeField(auto_created=True, verbose_name='date started'),
        ),
    ]
