# Generated by Django 3.2.9 on 2021-11-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0010_run_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='date',
        ),
    ]
