# Generated by Django 3.2.9 on 2021-11-24 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0011_remove_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date executed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='run',
            name='pipeline_command',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
