# Generated by Django 3.2.9 on 2021-11-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0012_auto_20211124_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='date',
        ),
    ]
