# Generated by Django 3.2.9 on 2021-11-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0013_remove_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='duration'),
        ),
    ]
