# Generated by Django 3.2.9 on 2021-11-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0014_run_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='pipeline_command',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
