# Generated by Django 3.2.9 on 2021-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0015_alter_run_pipeline_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='duration'),
        ),
    ]
