# Generated by Django 3.2.10 on 2021-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0016_alter_run_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='pipeline_command',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
