# Generated by Django 3.2.6 on 2022-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0018_run_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='parent_run_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='post_status',
            field=models.BooleanField(default=False, verbose_name='post worklow'),
        ),
    ]
