# Generated by Django 3.2.9 on 2021-11-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_pipeline_name', models.CharField(max_length=80)),
                ('short_pipe', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('short', models.CharField(max_length=50)),
                ('base_pipe_name_wo', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=50)),
                ('base_pipeline', models.CharField(default='RNA-Seq', max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('short', models.CharField(default='postrna', max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('sorting_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetPipelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=80)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('target_destination', models.CharField(max_length=50)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.dataset')),
            ],
        ),
    ]
