# Generated by Django 3.2.10 on 2021-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='datasetpipelines',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
