# Generated by Django 3.2.10 on 2021-12-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_auto_20211216_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpipelines',
            name='short_description',
            field=models.TextField(max_length=2000),
        ),
    ]
